apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: raj
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: hello-world
        name: raj
        resources: {}
      restartPolicy: Never
status: {}
